### ISSUE TITLE
incompatible

### ISSUE THREAD

**Issue by TT20240612** [John-WL/sd-webui-inpaint-background#13]
Win11 The plug-in is not displayed in the label bar after the system is installed               Win11  系统不支持插件 安装好后 SD 界面不显示  经测试 win10最新版可用

**Comment by John-WL** [comment]
That is surprising to me, as the UI should be OS agnostic. Do you have any errors in the console? 

I will likely update the UI in a few months to remove a strong patch that was introduced with Webui 1.9, maybe this will fix the issue. This is not clear yet. 

I don't have windows 11 and it would require a significant amount of time and effort for me to diagnose the issue and fix it. Because of this, I'm affraid windows 11 will probably not be supported actively going forward.

**Comment by John-WL** [comment]
Closing this as no updates from OP for almost a month now. Do let me know if this is still an issue.
