### ISSUE TITLE
Alpha matting settings don't do anything?

### ISSUE THREAD

**Issue by YourFriendlyNeighborhoodMONKE** [John-WL/sd-webui-inpaint-background#4]
Hi,

Thank you for this contribution!

For some reason when I tick alpha matting setting on and try to make adjustments to the mask, they don't seem to do anything as they normally would with rembg

Am I missing something?

**Comment by John-WL** [comment]
Thank you for bringing this up! I wasn't sure if it was normal or not, and I rarely use it. I'll investigate, it's probably a dumb overlook by me.

**Comment by YourFriendlyNeighborhoodMONKE** [comment]
Thanks for quick response!

None of the different models seem to affect the mask either

I know from using rembg they have huge differences
The image seems to reload and re-process, but nothing changes with the mask

Also, I've only tested the plugin on the Forge repo so far

**Comment by John-WL** [comment]
I am confident the issue is in the extension (I'm on plain old A1111).

**Comment by John-WL** [comment]
Reference for comarision:
https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg/blob/master/scripts%2Fpostprocessing_rembg.py

Sorry, I've been more busy than I thought I would be last week. I'll try to look into it this week.

**Comment by John-WL** [comment]
Okay I found why it's not working! 
Essentially, when you call `rembg.remove` with `return_mask=True`, it doesn't process the mask with alpha matting. It just returns it as-is. You would expect otherwise from how the function looks, but I guess that's just how it is. 

The solution is to return the image without the background, and then resolve the mask manually from the result. 
I'll see if I can actually resolve the mask or not from that.
